name: QA Daily Data Refresh
on:
  schedule:
    - cron: '*/5 * * * *'
    #every five minutes
  workflow_dispatch:

jobs:
  retrigger-workflows-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: vanstinator/re-run-open-prs-on-base-update@v1.4.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          skip_failed_runs: false
          require_label_regex: daily_refresh
